// Fastify plugin autogenerated by fastify-openapi-glue
import { FastifyInstance } from 'fastify'
import openapiGlue from "fastify-openapi-glue";
import service from "./service.js";
import securityHandlers from "./security.js";
import { URL } from "url";
const localFile = ( fileName:string ) => (new URL(fileName,import.meta.url)).pathname

const options = {
  specification: localFile('../openApi.json'),
  service,
  securityHandlers
};

export default async function (fastify:FastifyInstance, opts:any) {
  fastify.register(openapiGlue, options);
};
